
import { Country } from './types';

export const COUNTRIES: Country[] = [
  { name: "Afghanistan", code: "AF", continent: "Asia", capital: "Kabul" },
  { name: "Albania", code: "AL", continent: "Europe", capital: "Tirana" },
  { name: "Algeria", code: "DZ", continent: "Africa", capital: "Algiers" },
  { name: "Andorra", code: "AD", continent: "Europe", capital: "Andorra la Vella" },
  { name: "Angola", code: "AO", continent: "Africa", capital: "Luanda" },
  { name: "Antigua and Barbuda", code: "AG", continent: "North America", capital: "Saint John's" },
  { name: "Argentina", code: "AR", continent: "South America", capital: "Buenos Aires" },
  { name: "Armenia", code: "AM", continent: "Asia", capital: "Yerevan" },
  { name: "Australia", code: "AU", continent: "Oceania", capital: "Canberra" },
  { name: "Austria", code: "AT", continent: "Europe", capital: "Vienna" },
  { name: "Azerbaijan", code: "AZ", continent: "Asia", capital: "Baku" },
  { name: "Bahamas", code: "BS", continent: "North America", capital: "Nassau" },
  { name: "Bahrain", code: "BH", continent: "Asia", capital: "Manama" },
  { name: "Bangladesh", code: "BD", continent: "Asia", capital: "Dhaka" },
  { name: "Barbados", code: "BB", continent: "North America", capital: "Bridgetown" },
  { name: "Belarus", code: "BY", continent: "Europe", capital: "Minsk" },
  { name: "Belgium", code: "BE", continent: "Europe", capital: "Brussels" },
  { name: "Belize", code: "BZ", continent: "North America", capital: "Belmopan" },
  { name: "Benin", code: "BJ", continent: "Africa", capital: "Porto-Novo" },
  { name: "Bhutan", code: "BT", continent: "Asia", capital: "Thimphu" },
  { name: "Bolivia", code: "BO", continent: "South America", capital: "Sucre" },
  { name: "Bosnia and Herzegovina", code: "BA", continent: "Europe", capital: "Sarajevo" },
  { name: "Botswana", code: "BW", continent: "Africa", capital: "Gaborone" },
  { name: "Brazil", code: "BR", continent: "South America", capital: "Brasília" },
  { name: "Brunei", code: "BN", continent: "Asia", capital: "Bandar Seri Begawan" },
  { name: "Bulgaria", code: "BG", continent: "Europe", capital: "Sofia" },
  { name: "Burkina Faso", code: "BF", continent: "Africa", capital: "Ouagadougou" },
  { name: "Burundi", code: "BI", continent: "Africa", capital: "Gitega" },
  { name: "Cabo Verde", code: "CV", continent: "Africa", capital: "Praia" },
  { name: "Cambodia", code: "KH", continent: "Asia", capital: "Phnom Penh" },
  { name: "Cameroon", code: "CM", continent: "Africa", capital: "Yaoundé" },
  { name: "Canada", code: "CA", continent: "North America", capital: "Ottawa" },
  { name: "Central African Republic", code: "CF", continent: "Africa", capital: "Bangui" },
  { name: "Chad", code: "TD", continent: "Africa", capital: "N'Djamena" },
  { name: "Chile", code: "CL", continent: "South America", capital: "Santiago" },
  { name: "China", code: "CN", continent: "Asia", capital: "Beijing" },
  { name: "Colombia", code: "CO", continent: "South America", capital: "Bogotá" },
  { name: "Comoros", code: "KM", continent: "Africa", capital: "Moroni" },
  { name: "Congo (Congo-Brazzaville)", code: "CG", continent: "Africa", capital: "Brazzaville" },
  { name: "Costa Rica", code: "CR", continent: "North America", capital: "San José" },
  { name: "Croatia", code: "HR", continent: "Europe", capital: "Zagreb" },
  { name: "Cuba", code: "CU", continent: "North America", capital: "Havana" },
  { name: "Cyprus", code: "CY", continent: "Europe", capital: "Nicosia" },
  { name: "Czechia (Czech Republic)", code: "CZ", continent: "Europe", capital: "Prague" },
  { name: "Denmark", code: "DK", continent: "Europe", capital: "Copenhagen" },
  { name: "Djibouti", code: "DJ", continent: "Africa", capital: "Djibouti" },
  { name: "Dominica", code: "DM", continent: "North America", capital: "Roseau" },
  { name: "Dominican Republic", code: "DO", continent: "North America", capital: "Santo Domingo" },
  { name: "Ecuador", code: "EC", continent: "South America", capital: "Quito" },
  { name: "Egypt", code: "EG", continent: "Africa", capital: "Cairo" },
  { name: "El Salvador", code: "SV", continent: "North America", capital: "San Salvador" },
  { name: "Equatorial Guinea", code: "GQ", continent: "Africa", capital: "Malabo" },
  { name: "Eritrea", code: "ER", continent: "Africa", capital: "Asmara" },
  { name: "Estonia", code: "EE", continent: "Europe", capital: "Tallinn" },
  { name: "Eswatini", code: "SZ", continent: "Africa", capital: "Mbabane" },
  { name: "Ethiopia", code: "ET", continent: "Africa", capital: "Addis Ababa" },
  { name: "Fiji", code: "FJ", continent: "Oceania", capital: "Suva" },
  { name: "Finland", code: "FI", continent: "Europe", capital: "Helsinki" },
  { name: "France", code: "FR", continent: "Europe", capital: "Paris" },
  { name: "Gabon", code: "GA", continent: "Africa", capital: "Libreville" },
  { name: "Gambia", code: "GM", continent: "Africa", capital: "Banjul" },
  { name: "Georgia", code: "GE", continent: "Asia", capital: "Tbilisi" },
  { name: "Germany", code: "DE", continent: "Europe", capital: "Berlin" },
  { name: "Ghana", code: "GH", continent: "Africa", capital: "Accra" },
  { name: "Greece", code: "GR", continent: "Europe", capital: "Athens" },
  { name: "Grenada", code: "GD", continent: "North America", capital: "Saint George's" },
  { name: "Guatemala", code: "GT", continent: "North America", capital: "Guatemala City" },
  { name: "Guinea", code: "GN", continent: "Africa", capital: "Conakry" },
  { name: "Guinea-Bissau", code: "GW", continent: "Africa", capital: "Bissau" },
  { name: "Guyana", code: "GY", continent: "South America", capital: "Georgetown" },
  { name: "Haiti", code: "HT", continent: "North America", capital: "Port-au-Prince" },
  { name: "Holy See", code: "VA", continent: "Europe", capital: "Vatican City" },
  { name: "Honduras", code: "HN", continent: "North America", capital: "Tegucigalpa" },
  { name: "Hungary", code: "HU", continent: "Europe", capital: "Budapest" },
  { name: "Iceland", code: "IS", continent: "Europe", capital: "Reykjavik" },
  { name: "India", code: "IN", continent: "Asia", capital: "New Delhi" },
  { name: "Indonesia", code: "ID", continent: "Asia", capital: "Jakarta" },
  { name: "Iran", code: "IR", continent: "Asia", capital: "Tehran" },
  { name: "Iraq", code: "IQ", continent: "Asia", capital: "Baghdad" },
  { name: "Ireland", code: "IE", continent: "Europe", capital: "Dublin" },
  { name: "Israel", code: "IL", continent: "Asia", capital: "Jerusalem" },
  { name: "Italy", code: "IT", continent: "Europe", capital: "Rome" },
  { name: "Jamaica", code: "JM", continent: "North America", capital: "Kingston" },
  { name: "Japan", code: "JP", continent: "Asia", capital: "Tokyo" },
  { name: "Jordan", code: "JO", continent: "Asia", capital: "Amman" },
  { name: "Kazakhstan", code: "KZ", continent: "Asia", capital: "Nur-Sultan" },
  { name: "Kenya", code: "KE", continent: "Africa", capital: "Nairobi" },
  { name: "Kiribati", code: "KI", continent: "Oceania", capital: "Tarawa" },
  { name: "Kuwait", code: "KW", continent: "Asia", capital: "Kuwait City" },
  { name: "Kyrgyzstan", code: "KG", continent: "Asia", capital: "Bishkek" },
  { name: "Laos", code: "LA", continent: "Asia", capital: "Vientiane" },
  { name: "Latvia", code: "LV", continent: "Europe", capital: "Riga" },
  { name: "Lebanon", code: "LB", continent: "Asia", capital: "Beirut" },
  { name: "Lesotho", code: "LS", continent: "Africa", capital: "Maseru" },
  { name: "Liberia", code: "LR", continent: "Africa", capital: "Monrovia" },
  { name: "Libya", code: "LY", continent: "Africa", capital: "Tripoli" },
  { name: "Liechtenstein", code: "LI", continent: "Europe", capital: "Vaduz" },
  { name: "Lithuania", code: "LT", continent: "Europe", capital: "Vilnius" },
  { name: "Luxembourg", code: "LU", continent: "Europe", capital: "Luxembourg" },
  { name: "Madagascar", code: "MG", continent: "Africa", capital: "Antananarivo" },
  { name: "Malawi", code: "MW", continent: "Africa", capital: "Lilongwe" },
  { name: "Malaysia", code: "MY", continent: "Asia", capital: "Kuala Lumpur" },
  { name: "Maldives", code: "MV", continent: "Asia", capital: "Male" },
  { name: "Mali", code: "ML", continent: "Africa", capital: "Bamako" },
  { name: "Malta", code: "MT", continent: "Europe", capital: "Valletta" },
  { name: "Marshall Islands", code: "MH", continent: "Oceania", capital: "Majuro" },
  { name: "Mauritania", code: "MR", continent: "Africa", capital: "Nouakchott" },
  { name: "Mauritius", code: "MU", continent: "Africa", capital: "Port Louis" },
  { name: "Mexico", code: "MX", continent: "North America", capital: "Mexico City" },
  { name: "Micronesia", code: "FM", continent: "Oceania", capital: "Palikir" },
  { name: "Moldova", code: "MD", continent: "Europe", capital: "Chisinau" },
  { name: "Monaco", code: "MC", continent: "Europe", capital: "Monaco" },
  { name: "Mongolia", code: "MN", continent: "Asia", capital: "Ulaanbaatar" },
  { name: "Montenegro", code: "ME", continent: "Europe", capital: "Podgorica" },
  { name: "Morocco", code: "MA", continent: "Africa", capital: "Rabat" },
  { name: "Mozambique", code: "MZ", continent: "Africa", capital: "Maputo" },
  { name: "Myanmar (Burma)", code: "MM", continent: "Asia", capital: "Naypyidaw" },
  { name: "Namibia", code: "NA", continent: "Africa", capital: "Windhoek" },
  { name: "Nauru", code: "NR", continent: "Oceania", capital: "Yaren District" },
  { name: "Nepal", code: "NP", continent: "Asia", capital: "Kathmandu" },
  { name: "Netherlands", code: "NL", continent: "Europe", capital: "Amsterdam" },
  { name: "New Zealand", code: "NZ", continent: "Oceania", capital: "Wellington" },
  { name: "Nicaragua", code: "NI", continent: "North America", capital: "Managua" },
  { name: "Niger", code: "NE", continent: "Africa", capital: "Niamey" },
  { name: "Nigeria", code: "NG", continent: "Africa", capital: "Abuja" },
  { name: "North Korea", code: "KP", continent: "Asia", capital: "Pyongyang" },
  { name: "North Macedonia", code: "MK", continent: "Europe", capital: "Skopje" },
  { name: "Norway", code: "NO", continent: "Europe", capital: "Oslo" },
  { name: "Oman", code: "OM", continent: "Asia", capital: "Muscat" },
  { name: "Pakistan", code: "PK", continent: "Asia", capital: "Islamabad" },
  { name: "Palau", code: "PW", continent: "Oceania", capital: "Ngerulmud" },
  { name: "Palestine State", code: "PS", continent: "Asia", capital: "Jerusalem" },
  { name: "Panama", code: "PA", continent: "North America", capital: "Panama City" },
  { name: "Papua New Guinea", code: "PG", continent: "Oceania", capital: "Port Moresby" },
  { name: "Paraguay", code: "PY", continent: "South America", capital: "Asunción" },
  { name: "Peru", code: "PE", continent: "South America", capital: "Lima" },
  { name: "Philippines", code: "PH", continent: "Asia", capital: "Manila" },
  { name: "Poland", code: "PL", continent: "Europe", capital: "Warsaw" },
  { name: "Portugal", code: "PT", continent: "Europe", capital: "Lisbon" },
  { name: "Qatar", code: "QA", continent: "Asia", capital: "Doha" },
  { name: "Romania", code: "RO", continent: "Europe", capital: "Bucharest" },
  { name: "Russia", code: "RU", continent: "Europe/Asia", capital: "Moscow" },
  { name: "Rwanda", code: "RW", continent: "Africa", capital: "Kigali" },
  { name: "Saint Kitts and Nevis", code: "KN", continent: "North America", capital: "Basseterre" },
  { name: "Saint Lucia", code: "LC", continent: "North America", capital: "Castries" },
  { name: "Saint Vincent and the Grenadines", code: "VC", continent: "North America", capital: "Kingstown" },
  { name: "Samoa", code: "WS", continent: "Oceania", capital: "Apia" },
  { name: "San Marino", code: "SM", continent: "Europe", capital: "San Marino" },
  { name: "Sao Tome and Principe", code: "ST", continent: "Africa", capital: "São Tomé" },
  { name: "Saudi Arabia", code: "SA", continent: "Asia", capital: "Riyadh" },
  { name: "Senegal", code: "SN", continent: "Africa", capital: "Dakar" },
  { name: "Serbia", code: "RS", continent: "Europe", capital: "Belgrade" },
  { name: "Seychelles", code: "SC", continent: "Africa", capital: "Victoria" },
  { name: "Sierra Leone", code: "SL", continent: "Africa", capital: "Freetown" },
  { name: "Singapore", code: "SG", continent: "Asia", capital: "Singapore" },
  { name: "Slovakia", code: "SK", continent: "Europe", capital: "Bratislava" },
  { name: "Slovenia", code: "SI", continent: "Europe", capital: "Ljubljana" },
  { name: "Solomon Islands", code: "SB", continent: "Oceania", capital: "Honiara" },
  { name: "Somalia", code: "SO", continent: "Africa", capital: "Mogadishu" },
  { name: "South Africa", code: "ZA", continent: "Africa", capital: "Pretoria" },
  { name: "South Korea", code: "KR", continent: "Asia", capital: "Seoul" },
  { name: "South Sudan", code: "SS", continent: "Africa", capital: "Juba" },
  { name: "Spain", code: "ES", continent: "Europe", capital: "Madrid" },
  { name: "Sri Lanka", code: "LK", continent: "Asia", capital: "Sri Jayawardenepura Kotte" },
  { name: "Sudan", code: "SD", continent: "Africa", capital: "Khartoum" },
  { name: "Suriname", code: "SR", continent: "South America", capital: "Paramaribo" },
  { name: "Sweden", code: "SE", continent: "Europe", capital: "Stockholm" },
  { name: "Switzerland", code: "CH", continent: "Europe", capital: "Bern" },
  { name: "Syria", code: "SY", continent: "Asia", capital: "Damascus" },
  { name: "Taiwan", code: "TW", continent: "Asia", capital: "Taipei" },
  { name: "Tajikistan", code: "TJ", continent: "Asia", capital: "Dushanbe" },
  { name: "Tanzania", code: "TZ", continent: "Africa", capital: "Dodoma" },
  { name: "Thailand", code: "TH", continent: "Asia", capital: "Bangkok" },
  { name: "Timor-Leste", code: "TL", continent: "Asia", capital: "Dili" },
  { name: "Togo", code: "TG", continent: "Africa", capital: "Lomé" },
  { name: "Tonga", code: "TO", continent: "Oceania", capital: "Nuku'alofa" },
  { name: "Trinidad and Tobago", code: "TT", continent: "North America", capital: "Port of Spain" },
  { name: "Tunisia", code: "TN", continent: "Africa", capital: "Tunis" },
  { name: "Turkey", code: "TR", continent: "Asia/Europe", capital: "Ankara" },
  { name: "Turkmenistan", code: "TM", continent: "Asia", capital: "Ashgabat" },
  { name: "Tuvalu", code: "TV", continent: "Oceania", capital: "Funafuti" },
  { name: "Uganda", code: "UG", continent: "Africa", capital: "Kampala" },
  { name: "Ukraine", code: "UA", continent: "Europe", capital: "Kyiv" },
  { name: "United Arab Emirates", code: "AE", continent: "Asia", capital: "Abu Dhabi" },
  { name: "United Kingdom", code: "GB", continent: "Europe", capital: "London" },
  { name: "United States of America", code: "US", continent: "North America", capital: "Washington, D.C." },
  { name: "Uruguay", code: "UY", continent: "South America", capital: "Montevideo" },
  { name: "Uzbekistan", code: "UZ", continent: "Asia", capital: "Tashkent" },
  { name: "Vanuatu", code: "VU", continent: "Oceania", capital: "Port Vila" },
  { name: "Venezuela", code: "VE", continent: "South America", capital: "Caracas" },
  { name: "Vietnam", code: "VN", continent: "Asia", capital: "Hanoi" },
  { name: "Yemen", code: "YE", continent: "Asia", capital: "Sana'a" },
  { name: "Zambia", code: "ZM", continent: "Africa", capital: "Lusaka" },
  { name: "Zimbabwe", code: "ZW", continent: "Africa", capital: "Harare" }
];
